[package]
name = "atomizer"
version = "0.0.2"
authors = ["Nicole Mazzuca <npmazzuca@gmail.com>"]
edition = "2018"
description = "StableSet library, for interned data"
license = "Apache-2.0"

[dependencies]

[features]
nightly = []
